REF: Move citations out of 'Provenance', rename 'Peek' to 'Details', link to location for citations.
qiime2/q2view-old pull request #100
Opened 2019-06-24 18:07 UTC by Davrod29

2019-06-24 22:42 UTC, ebolyen requested changes
Looking really good @Davrod29! Just minor changes, and a slight reorganization of `citations.jsx` which will probably break imports in a few spots.

2019-06-24 22:42 UTC, ebolyen commented on app/pages/Peek/component.jsx
> +import Citations from '../Provenance/citations';
I think we should move this component into the current "module" of `Peek` (and perhaps rename `app/pages/Peek` to `app/pages/Details` to match the UI).

2019-06-24 22:42 UTC, ebolyen commented on app/pages/Provenance/citations.jsx
> +            <option value="apa">APA</option>
If we are ultimately unable to get any kind of bibtex parsing going, we should remember to remove the APA option, since it won't work.

2019-06-24 22:42 UTC, ebolyen commented on app/pages/Provenance/component.jsx
> +                            <a {...this.props.goToDetailsProps}> Link </a>
The whitespace is part of the link right now. Maybe: 

"Please follow [this link](#)."

2019-06-24 22:42 UTC, ebolyen commented on app/ToolbarWindow/Menu.jsx
> +                        <div className="hidden-xs" style={{ margin: '13px 10px 13px 10px', display: 'inline-block', float: 'left' }}>
This seems to work for local views, but I'm seeing the same overflow for "downloadable" views:
![image](https://user-images.githubusercontent.com/3976804/60056669-8c9ef800-9696-11e9-9d4f-e33b04762c67.png)

http://localhost:4242/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2019.4%2Fdata%2Ftutorials%2Fmoving-pictures%2Ftaxa-bar-plots.qzv

2019-06-25 20:54 UTC, Davrod29 commented on app/pages/Provenance/citations.jsx
> +            <option value="apa">APA</option>
I have removed the APA option until we are able to perform bibtex parsing. We can add that feature in with a different PR.

2019-06-25 20:54 UTC, Davrod29 commented on app/pages/Peek/component.jsx
> +import Citations from '../Provenance/citations';
The Peek folder has been renamed to Details, and the component now exists within that folder.

2019-06-25 20:55 UTC, Davrod29 commented on app/pages/Provenance/component.jsx
> +                            <a {...this.props.goToDetailsProps}> Link </a>
The new format for the link should now reflect the example provided.

2019-06-25 21:06 UTC, Davrod29 commented on app/ToolbarWindow/Menu.jsx
> +                        <div className="hidden-xs" style={{ margin: '13px 10px 13px 10px', display: 'inline-block', float: 'left' }}>
The favicon margin was returned to previous value, and the width for the NavBar component was reduced.

2019-06-27 17:06 UTC, ebolyen commented
@Davrod29 This looks really good to me, but there's a few `.DS_Stores` files in your PR, would you remove them, then I should be able to merge. Thanks! 

P.S. if you are feeling ambitious, it wouldn't hurt to put `.DS_Store` in the project's `.gitignore` file so that git will generally ignore those files on your machine, and anyone else on OS X.

2019-06-27 17:27 UTC, ebolyen approved these changes

2019-06-27 17:27 UTC, merged

2019-06-27 17:28 UTC, ebolyen commented
Thanks @Davrod29!

2019-07-10 16:39 UTC, thermokarst commented
When are we going to deploy these changes, @ebolyen?

2019-07-10 16:40 UTC, ebolyen commented
Soon! @Davrod29 is currently working on citation formatting as well, I was planning on bundling them all together in one push sometime in the next week or two.

2019-07-10 18:42 UTC, thermokarst commented
A thought just popped into my head: maybe we should hold off until the 2019.7 release, that way we can also include @Davrod29's new q2templates changes in the gallery visualizations?

2019-07-10 19:07 UTC, ebolyen commented
I would really like these changes for STAMPS, so I would prefer to do two builds in that case.