ENH: Style-matching and minor adjustements
qiime2/q2view-old pull request #37
Opened 2017-01-03 03:30 UTC by thermokarst

- Removes all `jumbotron`s in favor of `grid`s (to match other Q2 sites)
- Replaces square QIIME 2 logo with rect variant (matching other Q2 sites)
- Clean up iframe border and positioning
- Highlight currently selected tab in navbar
- Match HTML title styling with other Q2 sites
- Update branding position (right) and title (https://view.qiime2.org/)

2017-01-03 17:03 UTC, ebolyen requested changes
Thanks for trying to fix the terribleness of some of the bootstrap and CSS! Couple of issues though, because nothing every works right on every browser... 

Tested in Firefox 49.

2017-01-03 17:03 UTC, ebolyen commented on app/ToolbarWindow/Menu.jsx
>                      </a>
Without the brand, the padding gets odd in the menu when you resize to a mobile resolution. (Although the current behavior flips the order of the brand and logo, so it's not doing an amazing job as is)

2017-01-03 17:03 UTC, ebolyen commented on app/ToolbarWindow/Menu.jsx
> +                                https://view.qiime2.org/
The brand causes the collapse menu to break (in mobile resolution), I don't think it is meant to be inside `Navbar.Collapse`, we could make it a `NavItem` instead though.

2017-01-03 17:03 UTC, ebolyen commented on app/ToolbarWindow/Menu.jsx
> -                            q2view
What if this stayed put and was just `View`? Then it would match the title (the logo + this text would say `QIIME 2` `View`)

2017-01-03 17:03 UTC, ebolyen commented on app/pages/Home/component.jsx
> +        <Row><Col md={12} style={ { textAlign: 'center' } }>- or -</Col></Row>
The `- or -` is very small now and easy to miss, should we just drop it?

2017-01-03 17:03 UTC, ebolyen commented on app/ToolbarWindow/Content.jsx
> +    marginTop: '-20px',
This doesn't quite work, I'm still seeing some content clipping in the iframe on the bottom. The "air-quotes" around temporary are there for a reason. Godspeed in your quest!

2017-01-03 17:27 UTC, thermokarst commented on app/ToolbarWindow/Content.jsx
> +    marginTop: '-20px',
Bummer, this worked like a charm in Chrome.

2017-01-03 17:27 UTC, thermokarst commented on app/ToolbarWindow/Menu.jsx
> +                                https://view.qiime2.org/
:+1:

2017-01-03 17:28 UTC, thermokarst commented on app/pages/Home/component.jsx
> +        <Row><Col md={12} style={ { textAlign: 'center' } }>- or -</Col></Row>
Hmm, renders the same size as before in Chrome, will take a look in FF.

2017-01-03 17:29 UTC, thermokarst commented on app/ToolbarWindow/Menu.jsx
> -                            q2view
View makes sense if we move this back over to the left, which sounds good to me.

2017-01-03 23:55 UTC, thermokarst commented on app/ToolbarWindow/Menu.jsx
>                      </a>
<img width="356" alt="screen shot 2017-01-03 at 4 54 29 pm" src="https://cloud.githubusercontent.com/assets/274668/21627466/565c153a-d1d5-11e6-9bbf-9b7d8aa2f88f.png">

Just to confirm, is this what you are talking about here? Or is this fun-looking menu something else entirely?

2017-01-04 00:13 UTC, ebolyen commented on app/ToolbarWindow/Menu.jsx
>                      </a>
It's on this page, but it isn't the fun-looking menu from the `Navbar.Brand` comment below. If you look closely at the `qiime2` logo, you'll see that it doesn't have the same padding as the rest of the page. This isn't an issue on the current site, so I think moving the `Navbar.Brand` has something to do with it.

2017-01-04 00:41 UTC, thermokarst commented on app/ToolbarWindow/Menu.jsx
>                      </a>
Sorry, copied and pasted this comment into the wrong window, meant to ask for the one below, not on the logo padding. Thats what I get for jumping between desktop and mobile.

2017-01-04 04:42 UTC, thermokarst commented
Alright, a few updates:

- Replaced the QIIME 2 logo with a new prototype of a "QIIME 2 View" logo (and dropped text label)
- Cleaned up the navbar a bit so that the "hamburger" is hidden when no archive is loaded
- Tweaked the `- or -` text to beef up the size a bit.
- Reverted the `calc` hack back to where it was (with some minor adjustments). FWIW, the only reason that was tweaked in the first place was because I was fiddling with the margins, and one thing led to another, and dropping the `calc` jazz looked "good" (turns out the iframe was just truncated in a convenient location!). Anyway, after a bit of searching, I really can't think of a "better" way to make it happen --- most other solutions seem to do something like this, and this seems to be the least complicated offering!

Thanks @ebolyen! Let me know if you want to see any other changes, or if you uncover any lurking surprises!

<img width="354" alt="screen shot 2017-01-03 at 9 37 08 pm" src="https://cloud.githubusercontent.com/assets/274668/21631815/e3093874-d1fc-11e6-9e1f-dd523b4d7cec.png">
<img width="362" alt="screen shot 2017-01-03 at 9 37 27 pm" src="https://cloud.githubusercontent.com/assets/274668/21631819/eb0a1e12-d1fc-11e6-850d-2b1378ba49b2.png">
<img width="1440" alt="screen shot 2017-01-03 at 9 39 12 pm" src="https://cloud.githubusercontent.com/assets/274668/21631833/1cef50fa-d1fd-11e6-999a-212c7230d287.png">

2017-01-04 16:03 UTC, ebolyen requested changes
This is looking awesome @thermokarst!

2017-01-04 16:03 UTC, ebolyen commented on app/ToolbarWindow/Content.jsx
> -    overflow: 'auto'
`overflow: 'auto'` is needed for things like `/incompatible-browser/` in mobile view. Without it we don't get a scrollbar. (You can test this by using private browsing mode in Firefox, which disables service-workers and will bounce you to this page.)

2017-01-04 16:03 UTC, ebolyen commented on app/ToolbarWindow/Menu.jsx
> +import logo from './img/q2view.png';
This picture is very large, shouldn't it be scaled down a little? Or do retina displays change something here?

2017-01-04 16:03 UTC, ebolyen commented on app/ToolbarWindow/Menu.jsx
> +                         className={(this.props.location.pathname === '/visualization/') ? 'active': ''}>
awesome! :+1:

2017-01-04 16:03 UTC, ebolyen commented on app/pages/IncompatibleBrowser/index.js
> +        </p>
I think there needs to be just a little bit of whitespace on the page after this paragraph.

2017-01-04 16:04 UTC, ebolyen commented
This is good to go once the last comments are addressed!

2017-01-04 16:07 UTC, ebolyen commented on app/ToolbarWindow/Content.jsx
> -    overflow: 'auto'
...or you could just navigate to that page it turns out... I've been doing this the hard way!

2017-01-05 01:51 UTC, thermokarst commented on app/ToolbarWindow/Content.jsx
> -    overflow: 'auto'
I had a chrome extension installed that injected a whole boatload of custom css whenever I had devtools up (unbeknownst to me!), and it was applying an `overflow` attr as part of its payload, which is why this looked okay when I dropped it. Good catch!!

2017-01-05 02:11 UTC, thermokarst commented on app/ToolbarWindow/Menu.jsx
> +import logo from './img/q2view.png';
This was deliberate --- the displayed image is scaled to `40px` tall, but at a myriad of zoom levels the extra pixels keep things looking nice and crisp (while still looking good shrunk down to `40px` by default). Are you seeing something on your end that looks not so awesome? I'll update the logo to a smaller size (`300px` by `96px`), but not completely shrunk down to `40px`, so that we get a smaller file size (`~115kb` vs `~300kb`).

2017-01-05 16:21 UTC, ebolyen commented on app/ToolbarWindow/Menu.jsx
> +import logo from './img/q2view.png';
No it looks fine on modern browsers (though my ancient Opera made it super grainy), I just saw the diff and it seemed a little big. `300x96` sounds great.

2017-01-05 16:23 UTC, ebolyen approved these changes

2017-01-05 16:24 UTC, merged

2017-01-05 16:24 UTC, ebolyen commented
Thanks @thermokarst! :tada:

2017-01-05 16:29 UTC, ebolyen commented
Just pushed to the live site!