ENH: Add more examples to q2view gallery
qiime2/q2view-old pull request #93
Opened 2018-07-17 00:09 UTC by turanoo

Fixes #92

2018-07-17 00:39 UTC, turanoo commented
@nbokulich, would you be able to review this PR when you get the chance? I think the descriptions I put in for the example might need some touch-up. 

Thanks 😃

2018-07-17 18:16 UTC, thermokarst commented
@nbokulich - here is the rendered Gallery:

![screen shot 2018-07-17 at 11 15 19 am](https://user-images.githubusercontent.com/274668/42837366-c390c2ea-89b2-11e8-9131-55d082b9a29a.png)

2018-07-17 18:20 UTC, thermokarst requested changes
Thanks @turanoo --- I have a few requests, inline. Thanks!

2018-07-17 18:20 UTC, thermokarst commented on app/pages/Home/Gallery.jsx
> +import alpharareThumb from './img/alpha_rarefaction_thumb.png';
Can you match the naming convention used above? `alphaRareThumb`.

2018-07-17 18:20 UTC, thermokarst commented on app/pages/Home/Gallery.jsx
> +import alphasigThumb from './img/alpha_significance_thumb.png';
Can you match the naming convention used above? `alphaSigThumb`.

2018-07-17 18:20 UTC, thermokarst commented on app/pages/Home/Gallery.jsx
> +                            href={'/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2018.4%2Fdata%2F' +
Can you update this link to the 2018.6 docs, since we are already in here making changes.

2018-07-17 18:20 UTC, thermokarst commented on app/pages/Home/Gallery.jsx
> +                            href={'/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2018.4%2Fdata%2F' +
Can you update this link to the 2018.6 docs, since we are already in here making changes.

2018-07-17 18:20 UTC, thermokarst commented on app/pages/Home/Gallery.jsx
> +                            href={'/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2018.4%2Fdata%2F' +
Can you update this link to the 2018.6 docs, since we are already in here making changes.

2018-07-17 18:20 UTC, thermokarst commented on app/pages/Home/Gallery.jsx
> +                <Thumbnail src={taxaThumb} alt="Taxonomic Bar Plots">
@ebolyen - these cards seem like a good candidate for a new component. Maybe that could be a "rainy day" project for someone learning react...

2018-07-17 18:27 UTC, nbokulich approved these changes
LGTM thanks @turanoo !

2018-07-17 18:46 UTC, ebolyen commented on app/pages/Home/Gallery.jsx
> +                <Thumbnail src={taxaThumb} alt="Taxonomic Bar Plots">
That's a great idea

2018-07-18 03:45 UTC, thermokarst approved these changes

2018-07-18 03:47 UTC, merged